version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=brasfoot
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./sql/1_types.sql:/docker-entrypoint-initdb.d/1_types.sql
          - ./sql/2_triggers.sql:/docker-entrypoint-initdb.d/2_triggers.sql
          - ./sql/3_extensions.sql:/docker-entrypoint-initdb.d/3_extensions.sql
          - ./sql/4_create_tables.sql:/docker-entrypoint-initdb.d/4_create_tables.sql
          - ./sql/5_insert_coach.sql:/docker-entrypoint-initdb.d/5_insert_coach.sql
          - ./sql/6_insert_team.sql:/docker-entrypoint-initdb.d/6_insert_team.sql
          - ./sql/7_insert_player.sql:/docker-entrypoint-initdb.d/7_insert_player.sql
          - ./sql/8_insert_stadium.sql:/docker-entrypoint-initdb.d/8_insert_stadium.sql
          - ./sql/9_insert_trains.sql:/docker-entrypoint-initdb.d/9_insert_trains.sql
          - ./sql/a_10_insert_championship.sql:/docker-entrypoint-initdb.d/a_10_insert_championship.sql
          - ./sql/a_11_insert_match.sql:/docker-entrypoint-initdb.d/a_11_insert_match.sql
          - ./sql/a_12_insert_played_match.sql:/docker-entrypoint-initdb.d/a_12_insert_played_match.sql
          - ./sql/a_13_insert_lineup_match.sql:/docker-entrypoint-initdb.d/a_13_insert_lineup_match.sql
          - ./sql/a_14_insert_event.sql:/docker-entrypoint-initdb.d/a_14_insert_event.sql
          - ./sql/a_15_insert_finance.sql:/docker-entrypoint-initdb.d/a_15_insert_finance.sql
          - ./sql/a_16_insert_transaction.sql:/docker-entrypoint-initdb.d/a_16_insert_transaction.sql